### ISSUE TITLE
tests: TestResolveTxnFallbackFromAsyncCommit is flaky

### ISSUE THREAD

**Issue by pingyu** [tikv/client-go#1145]
Version: [tidb-cse-7.5](https://github.com/tikv/client-go/tree/tidb-cse-7.5), f3d4bda9fd85d989feb75b8f026746455ecccd35

```
2024-01-27T01:33:49.7364174Z --- FAIL: TestAsyncCommit (124.78s)
2024-01-27T01:33:49.7597390Z     --- FAIL: TestAsyncCommit/TestResolveTxnFallbackFromAsyncCommit (117.10s)
2024-01-27T01:33:49.7598542Z         async_commit_test.go:508: 
2024-01-27T01:33:49.7600494Z             	Error Trace:	/home/runner/work/client-go/client-go/integration_tests/async_commit_test.go:508
2024-01-27T01:33:49.7603120Z             	            				/home/runner/work/client-go/client-go/integration_tests/async_commit_test.go:558
2024-01-27T01:33:49.7606432Z             	Error:      	Expected nil, but got: &client.ErrConn{Err:wait recvLoop timeout,timeout:5µs, wait_duration:1.091µs:: context deadline exceeded, Addr:"127.0.0.1:20160", Ver:0x1}
2024-01-27T01:33:49.7608167Z             	Test:       	TestAsyncCommit/TestResolveTxnFallbackFromAsyncCommit
2024-01-27T01:33:49.7609467Z         suite.go:87: test panicked: runtime error: invalid memory address or nil pointer dereference
2024-01-27T01:33:49.7610266Z             goroutine 3290 [running]:
2024-01-27T01:33:49.7610768Z             runtime/debug.Stack()
2024-01-27T01:33:49.7611579Z             	/opt/hostedtoolcache/go/1.21.0/x64/src/runtime/debug/stack.go:24 +0x5e
2024-01-27T01:33:49.7612741Z             github.com/stretchr/testify/suite.failOnPanic(0xc0008d4820, {0x1d1b960, 0x3cf73f0})
2024-01-27T01:33:49.7614534Z             	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:87 +0x39
2024-01-27T01:33:49.7615882Z             github.com/stretchr/testify/suite.Run.func1.1()
2024-01-27T01:33:49.7617517Z             	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:183 +0x24c
2024-01-27T01:33:49.7618742Z             panic({0x1d1b960?, 0x3cf73f0?})
2024-01-27T01:33:49.7620027Z             	/opt/hostedtoolcache/go/1.21.0/x64/src/runtime/panic.go:914 +0x21f
2024-01-27T01:33:49.7622311Z             integration_tests_test.(*testAsyncCommitSuite).TestResolveTxnFallbackFromAsyncCommit.func2({0x1?}, 0x1, 0x1)
2024-01-27T01:33:49.7624598Z             	/home/runner/work/client-go/client-go/integration_tests/async_commit_test.go:509 +0x263
2024-01-27T01:33:49.7626546Z             integration_tests_test.(*testAsyncCommitSuite).TestResolveTxnFallbackFromAsyncCommit(0xc0003972c0)
2024-01-27T01:33:49.7628682Z             	/home/runner/work/client-go/client-go/integration_tests/async_commit_test.go:558 +0x4f8
2024-01-27T01:33:49.7630762Z             reflect.Value.call({0xc000987400?, 0xc0007cd8c8?, 0xc0000bc2d0?}, {0x2044af1, 0x4}, {0xc000bd1e70, 0x1, 0xc000bd1d78?})
2024-01-27T01:33:49.7632949Z             	/opt/hostedtoolcache/go/1.21.0/x64/src/reflect/value.go:596 +0xce7
2024-01-27T01:33:49.7634715Z             reflect.Value.Call({0xc000987400?, 0xc0007cd8c8?, 0xc0003972c0?}, {0xc000bd1e70?, 0x53388d?, 0x2f65900?})
2024-01-27T01:33:49.7636430Z             	/opt/hostedtoolcache/go/1.21.0/x64/src/reflect/value.go:380 +0xb9
2024-01-27T01:33:49.7637750Z             github.com/stretchr/testify/suite.Run.func1(0xc0008d4820)
2024-01-27T01:33:49.7639476Z             	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:197 +0x467
2024-01-27T01:33:49.7640760Z             testing.tRunner(0xc0008d4820, 0xc000c4d9e0)
2024-01-27T01:33:49.7642156Z             	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:1595 +0xff
2024-01-27T01:33:49.7643321Z             created by testing.(*T).Run in goroutine 2811
2024-01-27T01:33:49.7644679Z             	/opt/hostedtoolcache/go/1.21.0/x64/src/testing/testing.go:1648 +0x3ad
```

See https://github.com/tikv/client-go/actions/runs/7675400060/job/20921576515.

**Comment by pingyu** [comment]
Fixed by #1146
