### ISSUE TITLE
client panic when kill pd leader during br backup

### ISSUE THREAD

**Issue by Lily2025** [tikv/client-go#1357]
1、run br backup
2、kill pd leader
3、br backup failed
`panic: close of closed channel

goroutine 2822 [running]:
[github.com/tikv/client-go/v2/internal/client.(*batchConn).Close(...)](http://github.com/tikv/client-go/v2/internal/client.(*batchConn).Close(...))
	/root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client_batch.go:769](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client_batch.go:769)
[github.com/tikv/client-go/v2/internal/client.(*connArray).Close(0xc0004bb560)](http://github.com/tikv/client-go/v2/internal/client.(*connArray).Close(0xc0004bb560))
	/root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:330](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:330) +0xf6
[github.com/tikv/client-go/v2/internal/client.(*RPCClient).CloseAddr](http://github.com/tikv/client-go/v2/internal/client.(*RPCClient).CloseAddr)(0xc0007e3680, {0xc000f7e7d0, 0x44})
	/root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:797](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:797) +0x1e5
[github.com/tikv/client-go/v2/internal/client.(*RPCClient).recycleIdleConnArray(0xc0007e3680)](http://github.com/tikv/client-go/v2/internal/client.(*RPCClient).recycleIdleConnArray(0xc0007e3680))
	/root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client_batch.go:835](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client_batch.go:835) +0x1f7
created by [github.com/tikv/client-go/v2/internal/client.(*RPCClient).sendRequest](http://github.com/tikv/client-go/v2/internal/client.(*RPCClient).sendRequest) in goroutine 2821
	/root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:587](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:587) +0x34b`

**Comment by crazycs520** [comment]
fixed by https://github.com/tikv/client-go/pull/1359

**Comment by crazycs520** [comment]
/affect-8.1
/affect-8.0
/affect-7.5
/affect-6.5
