### ISSUE TITLE
Client-go panic when time jump back

### ISSUE THREAD

**Issue by Defined2014** [tikv/client-go#1514]
Panic stack, version v6.5.3

```
panic: counter cannot decrease in value
goroutine 4663549101 [running]:
github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc09e568000?, 0xbf662eadbd67ffef?)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/counter.go:109 +0xf4
github.com/tikv/client-go/v2/internal/client.(*RPCClient).updateTiKVSendReqHistogram(0x7f704b1e8631?, 0xc5bec28000, 0x7e01618?, {0x1823683?, 0x1882367?, 0x7dcd520?}, 0x0)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/client/client.go:438 +0x86a
github.com/tikv/client-go/v2/internal/client.(*RPCClient).sendRequest.func1()
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/client/client.go:483 +0x10d
github.com/tikv/client-go/v2/internal/client.(*RPCClient).sendRequest(0xc000d97dd0, {0x54dd9e8, 0xc35bfbeec0}, {0xc0012be020, 0xf}, 0xc5bec28000, 0x54dda90?)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/client/client.go:497 +0x625
github.com/tikv/client-go/v2/internal/client.(*RPCClient).SendRequest(0x4746960?, {0x54dd9e8, 0xc35bfbeec0}, {0xc0012be020, 0xf}, 0x0?, 0x1e3d0e0?)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/client/client.go:540 +0x78
github.com/tikv/client-go/v2/internal/client.interceptedClient.SendRequest({{0x54d4840?, 0xc000d97dd0?}}, {0x54dd9e8, 0xc35bfbeec0}, {0xc0012be020, 0xf}, 0xc01af9cf30?, 0xdf8475800)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/client/client_interceptor.go:42 +0x186
github.com/tikv/client-go/v2/internal/client.reqCollapse.SendRequest({{0x54db980?, 0xc000b12e80?}}, {0x54dd9e8, 0xc35bfbeec0}, {0xc0012be020, 0xf}, 0xc01af9cf80?, 0x18a7fd7?)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/client/client_collapse.go:74 +0xd6
github.com/tikv/client-go/v2/internal/locate.(*RegionRequestSender).sendReqToRegion(0xc01af9d900, 0xc3911c0b40, 0xc3ffb6ce80, 0xc5bec28000, 0xc01af9d778?)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/locate/region_request.go:1217 +0x897
github.com/tikv/client-go/v2/internal/locate.(*RegionRequestSender).SendReqCtx(0xc01af9d900, 0xc3911c0b40, 0xc5bec28000, {0x13116c4, 0x3445, 0x284e5}, 0xdf8475800, 0x0, {0x0, 0x0, ...})
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/locate/region_request.go:1046 +0x138a
github.com/tikv/client-go/v2/internal/locate.(*RegionRequestSender).SendReq(...)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/internal/locate/region_request.go:233
github.com/tikv/client-go/v2/tikv.(*KVStore).SendReq(0xc000b3c2c0, 0xc35bfbeec0?, 0xc42afa3ac0?, {0x7e01618?, 0xc000d68b70?, 0xc000b0e198?}, 0x5?)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/tikv/kv.go:421 +0xe5
github.com/pingcap/tidb/store/gcworker.(*GCWorker).resolveLocksForRange(0xc003f3d180, {0x54dd9e8, 0xc35bfbeec0}, 0xc01af9dd48?, 0x64dde0a53f00000, {0xc38d8c1f80, 0x13, 0x1b}, {0xc021c5fc80, 0x13, ...})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:1214 +0x3f9
github.com/pingcap/tidb/store/gcworker.(*GCWorker).legacyResolveLocks.func1({0x54dd9e8?, 0xc35bfbeec0?}, {{0xc38d8c1f80, 0x13, 0x1b}, {0xc021c5fc80, 0x13, 0x1b}})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:1081 +0x90
github.com/tikv/client-go/v2/txnkv/rangetask.(*rangeTaskWorker).run(0xc1b037ac00, {0x54dd9e8?, 0xc35bfbeec0?}, 0xc390b78b40)
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/txnkv/rangetask/range_task.go:302 +0x199
created by github.com/tikv/client-go/v2/txnkv/rangetask.(*Runner).RunOnRange
	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.4-0.20230612030254-5fde3098f918/txnkv/rangetask/range_task.go:156 +0x788
```

Seems the value of `elapsed.Seconds()` is negative.

**Comment by Defined2014** [comment]
`time.Now()` will not jump back, so I think the problem is related to OS or hardware rather than our code, close this issue.

https://pkg.go.dev/time#hdr-Monotonic_Clocks
